PR with schema, core and makefile changes
juxt/jinx pull request #5
Opened 2019-07-18 06:07 UTC by sunitakawane

2019-07-18 07:38 UTC, shivekkhurana requested changes

2019-07-18 07:38 UTC, shivekkhurana commented on src/juxt/jsonschema/core.cljc
>  (defn regex? [x]
`regex?` should return a boolean. The java version returns Pattern or map.

2019-07-18 07:38 UTC, shivekkhurana commented on deps.edn
> +               ;;refactor-nrepl {:mvn/version "2.3.1"}
Can get rid of this dep.

2019-07-18 07:38 UTC, shivekkhurana commented on Makefile
> +test-clj:
Tabs seem to be out of place. Use only a single tab (like `official-test`)

2019-07-18 09:34 UTC, shivekkhurana approved these changes

2019-07-19 14:44 UTC, malcolmsparks approved these changes
Yes, all good. Thanks

2019-07-19 14:44 UTC, merged